function [] = GUI_MAIN()

S.fh = figure('units','pixels',...
              'position',[600 400 150 230],...
              'menubar','none',...
              'name',' Segment',...
              'numbertitle','off',...
              'resize','off');
          
S.pb(1) = uicontrol('style','push',...
                 'unit','pix',...
                 'position',[20 20 110 30],...
                 'string','Whole Analysis',...
                 'callback',{@whole,S},...
                 'enable','on');
S.pb(2) = uicontrol('style','push',...
                 'unit','pix',...
                 'position',[20 60 110 30],...
                 'string','Colocalization',...
                 'callback',{@coloc,S},...
                 'enable','on');
S.pb(3) = uicontrol('style','push',...
                 'unit','pix',...
                 'position',[20 100 110 30],...
                 'string','Segmentation',...
                 'callback',{@segment,S},...
                 'enable','on');
S.pb(4) = uicontrol('style','push',...
                 'unit','pix',...
                 'position',[20 140 110 30],...
                 'string','Align sequences',...
                 'callback',{@align,S},...
                 'enable','on');         
                        
S.pb(5) = uicontrol('style','push',...
                 'unit','pix',...
                 'position',[20 180 110 30],...
                 'string','Stack sequences',...
                 'callback',{@stack,S},...
                 'enable','on');      
S.NAME = {'No sequence selected'};

             
    function [] = stack(varargin)
    % Callback for pushbutton.
             GUI_createstack
             set(S.fh,'DeleteFcn', @preCloseMain);
    end

    function [] = align(varargin)
    % Callback for pushbutton.
             GUI_align
             set(S.fh,'DeleteFcn', @preCloseMain);
    end

    function [] = segment(varargin)
    % Callback for pushbutton.
             GUI_segment
             set(S.fh,'DeleteFcn', @preCloseMain);
    end

    function [] = coloc(varargin)
    % Callback for pushbutton.
             GUI_colocalitzation
             set(S.fh,'DeleteFcn', @preCloseMain);
    end

    function [] = whole(varargin)
    % Callback for pushbutton.
             GUI_WHOLE
             set(S.fh,'DeleteFcn', @preCloseMain);
    end

    function preCloseMain(varargin)
      try 
%        fprintf('Closing non-main figures!\n');
        handles=findall(0,'type','figure'); % find all handles opened
        close(handles);
        close all;
      end 
%      fprintf('Closing main figure!\n');     
      delete(S.fh(1));
    end

end